CREATE TABLE IF NOT EXISTS interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    rating DECIMAL NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    UNIQUE (user_id, event_id)
);

CREATE TABLE IF NOT EXISTS similarities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event1 BIGINT NOT NULL,
    event2 BIGINT NOT NULL,
    similarity DECIMAL NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    UNIQUE (event1, event2)
);

CREATE INDEX idx_interactions_user_id ON interactions (user_id);
CREATE INDEX idx_interactions_event_id ON interactions (event_id);
CREATE INDEX idx_similarities_event1 ON similarities (event1);
CREATE INDEX idx_similarities_event2 ON similarities (event2);