grpc:
  server:
    port: 0

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

kafka:
  topics:
    user-action: stats.user-actions.v1