CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN
);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    paid BOOLEAN,
    participant_limit BIGINT,
    request_moderation BOOLEAN,
    initiator_id BIGINT NOT NULL,
    initiator_name VARCHAR(100),
    state VARCHAR(50),
    confirmed_requests INTEGER,
    created_on TIMESTAMP NOT NULL,
    published_on TIMESTAMP
);

CREATE TABLE IF NOT EXISTS compilation_event (
    compilation_id BIGINT REFERENCES compilations(id) ON DELETE CASCADE,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS views (
    id SERIAL PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    ip VARCHAR(45) NOT NULL,
    CONSTRAINT unique_event_ip UNIQUE (event_id, ip)
);

CREATE TABLE IF NOT EXISTS comments(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(500),
    created TIMESTAMP,
    name VARCHAR(100),
    title varchar(200),
    creator_id BIGINT ,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    state VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_events_initiator_id ON events (initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_category_id ON events (category_id);
CREATE INDEX IF NOT EXISTS idx_events_state ON events (state);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events (event_date);

CREATE INDEX IF NOT EXISTS idx_events_state_category_event_date ON events (state, category_id, event_date);
CREATE INDEX IF NOT EXISTS idx_events_published_on ON events (published_on);

CREATE INDEX IF NOT EXISTS idx_compilations_pinned ON compilations (pinned);
