#grpc:
#  server:
#    port: 0

spring:
  application:
    name: collector
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server

#server:
#  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10